import { Inter } from "next/font/google";
import { Anton } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const anton = Anton({subsets:["latin"],weight:["400"]});

export const metadata = {
  title: "ISTE-VIT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${anton.className} bg-white text-black overflow-x-hidden`}>
        <div className="m-auto min-h-screen flex flex-col justify-between">
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
